@startuml Seq_addWheel
title addWheel(int pos) - Diagrama de Secuencia Detallado
skinparam shadowing false
autonumber

actor Usuario
participant SlotMachine
participant BodyMachine
participant Wheel
participant Symbol
participant Circle
participant Triangle
participant Rectangle
participant Canvas

Usuario -> SlotMachine: addWheel(pos)
activate SlotMachine

opt wheels.size() < 5
    SlotMachine -> Wheel: <<create>> new Wheel()
    activate Wheel

    Wheel -> Circle: <<create>> wheel = new Circle()
    activate Circle
    Circle --> Wheel
    deactivate Circle

    Wheel -> Circle: wheel.changeSize(45)
    activate Circle
    Circle --> Wheel
    deactivate Circle

    Wheel -> Circle: wheel.changeColor(gray)
    activate Circle
    Circle --> Wheel
    deactivate Circle

    Wheel -> Circle: <<create>> symbolCircle = new Circle()
    activate Circle
    Circle --> Wheel
    deactivate Circle

    Wheel -> Triangle: <<create>> symbolTriangle = new Triangle()
    activate Triangle
    Triangle --> Wheel
    deactivate Triangle

    Wheel -> Rectangle: <<create>> symbolRectangle = new Rectangle()
    activate Rectangle
    Rectangle --> Wheel
    deactivate Rectangle

    Wheel -> Circle: symbolCircle.changeSize(20)
    activate Circle
    Circle --> Wheel
    deactivate Circle

    Wheel -> Triangle: symbolTriangle.changeSize(20, 20)
    activate Triangle
    Triangle --> Wheel
    deactivate Triangle

    Wheel -> Rectangle: symbolRectangle.changeSize(20, 20)
    activate Rectangle
    Rectangle --> Wheel
    deactivate Rectangle

    Wheel --> SlotMachine
    deactivate Wheel

    loop i = 0 to wheels.size() - 1
        SlotMachine -> Wheel: wheels.get(i).setPosition(x, y)
        activate Wheel

        Wheel -> Circle: wheel.moveHorizontal(diffX)
        activate Circle
        Circle --> Wheel
        deactivate Circle

        Wheel -> Circle: wheel.moveVertical(diffY)
        activate Circle
        Circle --> Wheel
        deactivate Circle

        Wheel -> Circle: symbolCircle.moveHorizontal(diffX)
        activate Circle
        Circle --> Wheel
        deactivate Circle

        Wheel -> Circle: symbolCircle.moveVertical(diffY)
        activate Circle
        Circle --> Wheel
        deactivate Circle

        Wheel -> Triangle: symbolTriangle.moveHorizontal(diffX)
        activate Triangle
        Triangle --> Wheel
        deactivate Triangle

        Wheel -> Triangle: symbolTriangle.moveVertical(diffY)
        activate Triangle
        Triangle --> Wheel
        deactivate Triangle

        Wheel -> Rectangle: symbolRectangle.moveHorizontal(diffX)
        activate Rectangle
        Rectangle --> Wheel
        deactivate Rectangle

        Wheel -> Rectangle: symbolRectangle.moveVertical(diffY)
        activate Rectangle
        Rectangle --> Wheel
        deactivate Rectangle

        opt visible
            Wheel -> Circle: symbolCircle.makeInvisible()
            activate Circle
            Circle -> Canvas: canvas.erase(this)
            activate Canvas
            Canvas --> Circle
            deactivate Canvas
            Circle --> Wheel
            deactivate Circle

            Wheel -> Triangle: symbolTriangle.makeInvisible()
            activate Triangle
            Triangle -> Canvas: canvas.erase(this)
            activate Canvas
            Canvas --> Triangle
            deactivate Canvas
            Triangle --> Wheel
            deactivate Triangle

            Wheel -> Rectangle: symbolRectangle.makeInvisible()
            activate Rectangle
            Rectangle -> Canvas: canvas.erase(this)
            activate Canvas
            Canvas --> Rectangle
            deactivate Canvas
            Rectangle --> Wheel
            deactivate Rectangle
        end

        Wheel --> SlotMachine
        deactivate Wheel
    end

    loop i = 0 to gallery.size() - 1
        SlotMachine -> Wheel: wheel.addSymbol(i + 1, gallery.get(i))
        activate Wheel
        Wheel --> SlotMachine
        deactivate Wheel
    end

    SlotMachine -> Wheel: wheels.get(0).getShownSymbol()
    activate Wheel
    Wheel --> SlotMachine
    deactivate Wheel

    loop i = 1 to wheels.size() - 1
        SlotMachine -> Wheel: wheels.get(i).getShownSymbol()
        activate Wheel
        Wheel --> SlotMachine
        deactivate Wheel

        SlotMachine -> Symbol: current.getColor()
        activate Symbol
        Symbol --> SlotMachine
        deactivate Symbol

        SlotMachine -> Symbol: first.getColor()
        activate Symbol
        Symbol --> SlotMachine
        deactivate Symbol
    end

    alt esJackpot
        SlotMachine -> BodyMachine: body.get(0).changeColor()
        activate BodyMachine

        BodyMachine -> Rectangle: body.changeColor(yellow)
        activate Rectangle

        Rectangle -> Canvas: canvas.draw(this, color, shape)
        activate Canvas
        Canvas --> Rectangle
        deactivate Canvas

        Rectangle --> BodyMachine
        deactivate Rectangle

        BodyMachine --> SlotMachine
        deactivate BodyMachine

    else noJackpot
        SlotMachine -> BodyMachine: body.get(0).normalColor()
        activate BodyMachine

        BodyMachine -> Rectangle: body.changeColor(blue)
        activate Rectangle

        Rectangle -> Canvas: canvas.draw(this, color, shape)
        activate Canvas
        Canvas --> Rectangle
        deactivate Canvas

        Rectangle --> BodyMachine
        deactivate Rectangle

        BodyMachine --> SlotMachine
        deactivate BodyMachine
    end

    SlotMachine -> BodyMachine: body.get(0).isVisible()
    activate BodyMachine
    BodyMachine --> SlotMachine
    deactivate BodyMachine

    opt body.get(0).isVisible()
        SlotMachine -> BodyMachine: body.get(0).makeVisible()
        activate BodyMachine

        BodyMachine -> Rectangle: body.makeVisible()
        activate Rectangle

        Rectangle -> Canvas: canvas.draw(this, color, shape)
        activate Canvas
        Canvas --> Rectangle
        deactivate Canvas

        Rectangle --> BodyMachine
        deactivate Rectangle

        BodyMachine --> SlotMachine
        deactivate BodyMachine

        loop i = 0 to wheels.size() - 1
            SlotMachine -> Wheel: wheels.get(i).makeVisible()
            activate Wheel

            Wheel -> Circle: wheel.makeVisible()
            activate Circle

            Circle -> Canvas: canvas.setVisible(true)
            activate Canvas
            Canvas --> Circle
            deactivate Canvas

            Circle -> Canvas: canvas.draw(this, color, shape)
            activate Canvas
            Canvas --> Circle
            deactivate Canvas

            Circle --> Wheel
            deactivate Circle

            Wheel -> Circle: symbolCircle.makeInvisible()
            activate Circle
            Circle -> Canvas: canvas.erase(this)
            activate Canvas
            Canvas --> Circle
            deactivate Canvas
            Circle --> Wheel
            deactivate Circle

            Wheel -> Triangle: symbolTriangle.makeInvisible()
            activate Triangle
            Triangle -> Canvas: canvas.erase(this)
            activate Canvas
            Canvas --> Triangle
            deactivate Canvas
            Triangle --> Wheel
            deactivate Triangle

            Wheel -> Rectangle: symbolRectangle.makeInvisible()
            activate Rectangle
            Rectangle -> Canvas: canvas.erase(this)
            activate Canvas
            Canvas --> Rectangle
            deactivate Canvas
            Rectangle --> Wheel
            deactivate Rectangle

            alt shownSymbol.getType() == TypeSymbol.CIRCLE
                Wheel -> Circle: symbolCircle.moveHorizontal(dx)
                activate Circle
                Circle -> Canvas: canvas.erase(this)
                activate Canvas
                Canvas --> Circle
                deactivate Canvas
                Circle -> Canvas: canvas.draw(this, color, shape)
                activate Canvas
                Canvas --> Circle
                deactivate Canvas
                Circle --> Wheel
                deactivate Circle

                Wheel -> Circle: symbolCircle.moveVertical(dy)
                activate Circle
                Circle -> Canvas: canvas.erase(this)
                activate Canvas
                Canvas --> Circle
                deactivate Canvas
                Circle -> Canvas: canvas.draw(this, color, shape)
                activate Canvas
                Canvas --> Circle
                deactivate Canvas
                Circle --> Wheel
                deactivate Circle

                Wheel -> Symbol: symbol.getColor()
                activate Symbol
                Symbol --> Wheel
                deactivate Symbol

                Wheel -> Circle: symbolCircle.changeColor(color)
                activate Circle
                Circle -> Canvas: canvas.draw(this, color, shape)
                activate Canvas
                Canvas --> Circle
                deactivate Canvas
                Circle --> Wheel
                deactivate Circle

                Wheel -> Circle: symbolCircle.makeVisible()
                activate Circle
                Circle -> Canvas: canvas.setVisible(true)
                activate Canvas
                Canvas --> Circle
                deactivate Canvas
                Circle -> Canvas: canvas.draw(this, color, shape)
                activate Canvas
                Canvas --> Circle
                deactivate Canvas
                Circle --> Wheel
                deactivate Circle

            else shownSymbol.getType() == TypeSymbol.TRIANGLE
                Wheel -> Triangle: symbolTriangle.moveHorizontal(dx)
                activate Triangle
                Triangle -> Canvas: canvas.erase(this)
                activate Canvas
                Canvas --> Triangle
                deactivate Canvas
                Triangle -> Canvas: canvas.draw(this, color, shape)
                activate Canvas
                Canvas --> Triangle
                deactivate Canvas
                Triangle --> Wheel
                deactivate Triangle

                Wheel -> Triangle: symbolTriangle.moveVertical(dy)
                activate Triangle
                Triangle -> Canvas: canvas.erase(this)
                activate Canvas
                Canvas --> Triangle
                deactivate Canvas
                Triangle -> Canvas: canvas.draw(this, color, shape)
                activate Canvas
                Canvas --> Triangle
                deactivate Canvas
                Triangle --> Wheel
                deactivate Triangle

                Wheel -> Symbol: symbol.getColor()
                activate Symbol
                Symbol --> Wheel
                deactivate Symbol

                Wheel -> Triangle: symbolTriangle.changeColor(color)
                activate Triangle
                Triangle -> Canvas: canvas.draw(this, color, shape)
                activate Canvas
                Canvas --> Triangle
                deactivate Canvas
                Triangle --> Wheel
                deactivate Triangle

                Wheel -> Triangle: symbolTriangle.makeVisible()
                activate Triangle
                Triangle -> Canvas: canvas.draw(this, color, shape)
                activate Canvas
                Canvas --> Triangle
                deactivate Canvas
                Triangle --> Wheel
                deactivate Triangle

            else shownSymbol.getType() == TypeSymbol.RECTANGLE
                Wheel -> Rectangle: symbolRectangle.moveHorizontal(dx)
                activate Rectangle
                Rectangle -> Canvas: canvas.erase(this)
                activate Canvas
                Canvas --> Rectangle
                deactivate Canvas
                Rectangle -> Canvas: canvas.draw(this, color, shape)
                activate Canvas
                Canvas --> Rectangle
                deactivate Canvas
                Rectangle --> Wheel
                deactivate Rectangle

                Wheel -> Rectangle: symbolRectangle.moveVertical(dy)
                activate Rectangle
                Rectangle -> Canvas: canvas.erase(this)
                activate Canvas
                Canvas --> Rectangle
                deactivate Canvas
                Rectangle -> Canvas: canvas.draw(this, color, shape)
                activate Canvas
                Canvas --> Rectangle
                deactivate Canvas
                Rectangle --> Wheel
                deactivate Rectangle

                Wheel -> Symbol: symbol.getColor()
                activate Symbol
                Symbol --> Wheel
                deactivate Symbol

                Wheel -> Rectangle: symbolRectangle.changeColor(color)
                activate Rectangle
                Rectangle -> Canvas: canvas.draw(this, color, shape)
                activate Canvas
                Canvas --> Rectangle
                deactivate Canvas
                Rectangle --> Wheel
                deactivate Rectangle

                Wheel -> Rectangle: symbolRectangle.makeVisible()
                activate Rectangle
                Rectangle -> Canvas: canvas.draw(this, color, shape)
                activate Canvas
                Canvas --> Rectangle
                deactivate Canvas
                Rectangle --> Wheel
                deactivate Rectangle
            end

            Wheel --> SlotMachine
            deactivate Wheel
        end
    end
end

SlotMachine --> Usuario
deactivate SlotMachine
@enduml
